//
// Created by Lukas Kellenberger on 11.04.17.
//

#ifndef IMMIX_CONSTANTS_H
#define IMMIX_CONSTANTS_H

#define LOG_BYTES_IN_ADDRESS ((byte_t) 3)
#define BYTES_IN_ADDRESS (1 << LOG_BYTES_IN_ADDRESS)
#define LOG_BITS_IN_ADDRESS (LOG_BITS_IN_BYTE + LOG_BYTES_IN_ADDRESS)
#define BITS_IN_ADDRESS (1 << LOG_BITS_IN_ADDRESS)

#define LOG_BYTES_IN_WORD ((byte_t)LOG_BYTES_IN_ADDRESS)
#define BYTES_IN_WORD (1 << LOG_BYTES_IN_WORD)
#define LOG_BITS_IN_WORD (LOG_BITS_IN_BYTE + LOG_BYTES_IN_WORD)
#define BITS_IN_WORD (1 << LOG_BITS_IN_WORD)

#define LOG_BYTES_IN_PAGE ((byte_t) 12)
#define BYTES_IN_PAGE (1 << LOG_BYTES_IN_PAGE)
#define LOG_BITS_IN_PAGE (LOG_BITS_IN_BYTE + LOG_BYTES_IN_PAGE)
#define BITS_IN_PAGE (1 << LOG_BITS_IN_PAGE)

#define LOG_BYTES_IN_SHORT 1


#endif //IMMIX_CONSTANTS_H
